InFact-coop/infactcoop.com

.eslintrc.json
.prettierignore
package-lock.json
package.json
src/components/background-img.js
src/components/clients.js
src/components/get-to-know-us.js
src/components/menu.js
src/components/our-work.js
src/components/overlay.js
src/components/section.js
src/components/work-content.js
src/containers/header.js
src/containers/headerLanding.js
src/containers/workContent.js
src/layouts/index.js
src/pages/about-us.js
src/pages/index.js

* Add eslint
* Fix linting errors

Add eslint and fix lint errors

---

src/components/about-pages.js
src/components/fac.js
src/components/get-to-know-us.js
src/components/header.js
src/components/menu.js
src/components/our-work.js
src/pages/our-approach.js

- corrects bg colours
- edits work cards to reflect deisgn

Landing edits

---

src/components/about-pages.js
src/components/clients.js
src/components/fac.js
src/components/get-to-know-us.js
src/components/header.js
src/components/menu.js
src/components/our-approach.js
src/components/our-work.js
src/components/section.js
src/components/work-content.js
src/pages/about-work-cast.js
src/pages/about-work-stimmy-things.js
src/pages/our-approach.js

- fixes header spacing
- edits height and width of images
- fixes font sizes and paragraph widths
- adds same title style as on landing page
Relates #37

Project page edits

---

src/components/menu.js
src/state/reducers.js
src/state/state.js
src/styles/style_animations.js
src/styles/style_utils.js

+ Added init state to menu
+ Factored out animations to separate file
+ Created menu animation
Relates #130

Menu animation

---

src/components/about-pages.js
src/components/contact-us.js
src/components/menu.js
src/components/overlay.js
src/pages/contact-us.js

- adds contact us page (relates #11)
- adds form with relevant inputs
- sets up formspree 
- adds contact page link to menu

Contact us

---

src/pages/our-approach.js

- adds extra spacing 
- fixes font to match rest of content
- edits mobile layout

Our approach edits

---

package-lock.json
package.json
src/components/about-us.js
src/components/footer.js
src/components/our-work.js
src/pages/about-us.js
src/pages/about-work-stimmy-things.js
src/styles/index.scss

relates #8 
Adds responsive photo sizing and layout but there's still a problem with the image aspect ratio 😢

About page design

---

package-lock.json
package.json
src/components/header.js
src/components/menu.js
src/containers/header-work.js
src/containers/header.js
src/state/actions.js
src/state/reducers.js

* Scroll to top on page change

Scroll to top on page change

---

src/components/header.js
src/components/our-work.js

+ Add animation to Cards
+ Remove button and make wrapper clickable
Relates #37

Cards animation

---

src/components/about-pages.js
src/components/about-us.js
src/components/card.js
src/components/contact-us.js
src/components/fac.js
src/components/footer.js
src/components/get-to-know-us.js
src/components/header.js
src/components/our-approach.js
src/components/work-card.js
src/components/work-content.js
src/pages/index.js
src/pages/our-approach.js
src/pages/our-work.js
src/pages/our-work/bluecross.js
src/pages/our-work/cast.js
src/styles/_custom.scss
src/styles/_variables.scss
src/styles/style_utils.js

* Add responsive styles for ipad

Ipad styling

---

package-lock.json
package.json
src/components/header.js
src/components/menu.js
src/pages/about-us.js
src/pages/contact-us.js
src/pages/index.js
src/pages/our-approach.js
src/pages/our-work.js
src/styles/_custom.scss
src/styles/style_utils.js

+ Navbar hidden fun 
+ Update npm packages
#37 :taco:

Hidden navbar

---

src/components/header.js

Center navbar

---

src/components/about-us.js
src/components/header.js
src/styles/style_utils.js

Make navbar less chunky

---

src/components/card.js
src/components/fac.js
src/components/get-to-know-us.js
src/components/our-approach.js
src/components/work-card.js
src/pages/our-work.js

* Fix work card spacing on mobile

Fix work-card spacing

---

src/components/header.js

* Make nav-bar full width again

Make navbar full-width

---

src/components/about-us.js
src/components/header.js
src/styles/style_utils.js

Fixed noga's dastardly grid and w-90 w-100-ns'ed the portraits

---

src/components/about-us.js
src/components/fac.js
src/components/menu.js
src/components/section.js
src/pages/our-approach.js
src/pages/our-work/coming-soon.js
src/styles/style_utils.js

Added internet explorer optimisations/bugfixes

---

src/components/contact-us.js
src/components/header.js
src/containers/header-work.js
src/pages/contact-us.js

Change contact us header

---

src/layouts/index.js

* Add description and keywords meta tags

Add description and keywords meta tags

---

src/components/work-card.js

Fix work cards on edge

---

src/state/reducers.js

Disable scrolling on open menu

---

src/state/reducers.js

Disable scroll on menu (iOS Solution)

---

src/components/fac.js
src/components/footer.js
src/components/layout.js
src/components/menu.js
src/pages/about-us.js
src/pages/contact-us.js
src/pages/index.js
src/pages/our-approach.js
src/pages/our-work.js
src/pages/our-work/bluecross.js

* Add title and met descriptions
* Reorder menu

Add titles and meta-descriptions

---

src/components/section.js
src/pages/about-us.js

Added co-op copy to website
